[pytest]
testpaths = Arkaie_Scraper/tests
python_files = *_test.py test_*.py
python_functions = test_*
# Redirects the cache to your local temp folder
cache_dir = C:\Users\mantheos\AppData\Local\Temp\pytest_cache