# download the link in each line of Aube.csv, which was generated by aube_civil_status_scraper.py

import os
csv_path = "Aube_test.csv"

for line in open(csv_path, "r", encoding="utf-8"):
    period, act_types, image_count, link = line.strip().split("|")
    for i in range(int(image_count)):
        mod_link = link.replace("image-1", f"image-{i+1}")
        # download the file at link and save it as {period}_{act_types}.pdf
        filename = f"Aube_{period}_{act_types}.pdf".replace("/", "-").replace(" ", "_")
        print(f"Downloading {filename} from {link}...")
        os.system(f"wget {link} -O '{filename}'")
